### ISSUE TITLE
active border not consistent with auro-input

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-dropdown#127]
## Describe the bug
The border for auro-combobox isn't consistent with auro-input.

## To Reproduce

View the combobox and compare it to auro input in the active state and focus state.  They seem to be fliped.

## Expected behavior

Consistent between all input types

**Comment by blackfalcon** [comment]
@braven112 can you please attach screenshots to help clarify the diff you are referring to?

**Comment by jason-capsule42** [comment]
@blackfalcon This is the issue we discussed about the active/focus states border/box-shadow width being reversed in dropdown compared auro-input.

**Comment by leeejune** [comment]
@jason-capsule42 Here's the blueprint: https://www.figma.com/file/3TQhiKjQqQOKYqaqcO1zj2/Dropdown?node-id=906%3A753
