### ISSUE TITLE
auro-dropdown: Default background doesn't match spec

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-dropdown#128]
## Describe the bug

auro-dropdowns default background is appearing transparent, rather than using var(--auro-color-background-lightest) as in the Figma spec.
Figma spec: https://www.figma.com/file/3TQhiKjQqQOKYqaqcO1zj2/Dropdown?node-id=906%3A753

## To Reproduce

1. Go to [auro.alaskaair.com](https://auro.alaskaair.com/components/auro/dropdown) and see that the dropdown background is transparent, which doesn't match the spec.

## Expected behavior

Expect dropdown background to match design spec, with token of var(--auro-color-background-lightest)

## Screenshots

Design spec:
![image](https://user-images.githubusercontent.com/34354487/172459861-ff23c07c-172a-4516-9faf-4e7ebc594fa7.png)

Live dropdown examples:
![image](https://user-images.githubusercontent.com/34354487/172459921-3a6e8121-ebc7-4c98-bc1a-31b14d1b46c7.png)

![image](https://user-images.githubusercontent.com/34354487/172460084-51b2353f-2fb7-4cd0-8966-f0b91f5251c7.png)

**Comment by blackfalcon** [comment]
This appears to be pretty straightforward. @jason-capsule42 maybe work with @leeejune for this fix?

**Comment by jason-capsule42** [comment]
I don't know if this was already fixed in a previous release or wasn't a valid bug to begin with but this doesn't appear to be an issue.

Spec linked calls for a background of `background: rgba(0, 0, 0, 0.06);`. Code is written `background-color: var(--auro-color-ui-bkg-hover-on-light);` which resolves to the same rgba value.

**Comment by leeejune** [comment]
![Screen Shot 2022-08-01 at 2 37 54 PM](https://user-images.githubusercontent.com/55998746/182250851-219224ad-ab37-4ecf-b355-a32ab8d08343.png)

Default state background should be `--auro-color-background-lightest`.
