### ISSUE TITLE
auro-icon not included as peer dependency

### ISSUE THREAD

**Issue by MattSidor** [AlaskaAirlines/auro-dropdown#137]
## Describe the bug

The optional `chevron` attribute uses `<auro-icon category="interface" name="arrow-down" />`, but `auro-icon` is not listed as a peer dependency in `package.json` or in the installation instructions.

## To Reproduce

1. Follow installation instructions for `auro-dropdown` in a project
2. Attempt to use `chevron` attribute
3. Note that the icon does not load unless you also separately install `auro-icon` in your project

## Expected behavior

- `@alaskaairux/auro-icon` in `peerDependencies` object of `package.json`
- installation instructions call out all required peer dependencies, including `auro-icon`

**Comment by jason-capsule42** [comment]
@MattSidor I'm going to be putting up a PR for a bunch of updates to dropdown today. I'm reassigning this to myself to include with that PR.

**Comment by MattSidor** [comment]
Thank you @jason-capsule42
