### ISSUE TITLE
auro-dropdown: create blueprint figma file

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-dropdown#14]
# General Support Request

The auro-dropdown is being reviewed for a new redesign of the common interface.

## Support request

Review the current state of the auro-dropdown design and develop a concept for a new interface.

## Possible Solution

Design to review current UI for new design opportunities.

## Exit criteria
- [x] complete blueprint work ([Link](https://www.figma.com/file/3TQhiKjQqQOKYqaqcO1zj2/Dropdown?node-id=906%3A753))
- [x] signoff from Auro engineering (TBD)
- [x] signoff by UI designers (Vidal Men)
- [x] consult with Auro engineering team for the creation of dev plan

**Comment by leeejune** [comment]
@blackfalcon I can't add/change labels...

**Comment by jason-capsule42** [comment]
The design for this needs to support both a version where we include the chevron and a version where we don't. Some use cases will have a trigger that needs to not have that icon present.

**Comment by jason-capsule42** [comment]
<img width="679" alt="Screen Shot 2021-11-16 at 9 14 16 AM" src="https://user-images.githubusercontent.com/23223137/142032995-945282fb-186d-4e3c-9fe5-ea2b7fdbbcef.png">

This looks like the box shadow is on the trigger?

I think the design needs to show the dropdown container itself even though it's empty. Does the dropdown container have a border or just the trigger? Or does it just have the drop shadow?

**Comment by jason-capsule42** [comment]
<img width="992" alt="Screen Shot 2021-11-16 at 9 30 11 PM" src="https://user-images.githubusercontent.com/23223137/142140576-56080f65-acda-4da4-bf10-2c2f811ef96b.png">

**Comment by jason-capsule42** [comment]
<img width="566" alt="Screen Shot 2021-11-16 at 9 32 16 PM" src="https://user-images.githubusercontent.com/23223137/142140800-fbb333f2-365b-4eb4-86fb-f1c4d74ab208.png">

**Comment by blackfalcon** [comment]
@jason-capsule42 the default should have a fill color like how we updated the checkbox to have a fill color. The rest with design is to place forms with light-gray backgrounds and the trigger needs to appear white. 

For an oonDark option, we would change that fill color. Which begs the question, I don't think we have any onDark UIs for these elements, do we?

**Comment by leeejune** [comment]
Updated dropdown with new style and edited the blueprint accordingly. Dropdown is updated to look more like the current input (label inside box).
