### ISSUE TITLE
Figma Component to match new features

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-dropdown#144]
# General Support Request

We need to update our figma component based off the the features in this issue #141 and this pr #142

**Comment by leeejune** [comment]
The Figma component will not be able to have adjustable sizing for the menu due to restraints in Figma components. By default it will match the width of the dropdown. However, I can add the sizing options to the blueprint.

**Comment by leeejune** [comment]
![Screen Shot 2022-08-01 at 2 21 49 PM](https://user-images.githubusercontent.com/55998746/182248876-aa9aef5a-0e41-4d47-87cf-f9724f72631d.png)

https://www.figma.com/file/nyXRAgG4YzZaGdIVmPwARP/Select?node-id=1313%3A1430

Added behavior specs to blueprint. @jason-capsule42 please review.
