### ISSUE TITLE
programmatic show example not working

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-dropdown#151]
## Describe the bug

The API example responsible for programmatically showing the dropdown content is not working as intended.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/dropdown/api.
1. Scroll down to `show` example.
1. See that the dropdown is not showing.

## Expected behavior

When the user starts typing into the input field, the dropdown should show.

## Screenshots

![Screen Shot 2022-08-29 at 5 02 21 PM](https://user-images.githubusercontent.com/55807669/187319398-a927aebd-11bc-448e-8825-e7fe8b87a892.png)

**Comment by blackfalcon** [comment]
@jordanjones243 this is marked as `review needed` but there is no linked PR?

**Comment by jordanjones243** [comment]
@blackfalcon There's no PR because I believe Jason said it once again coincides with his DocSite examples fix.
