### ISSUE TITLE
Placeholder and label text color should be grey

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-dropdown#166]
## Describe the bug
The placeholder and label text color in an unfilled state is currently black.

## To Reproduce

1. See text color of dropdown in its default state.

## Expected behavior

The placeholder or label text should be `auro-color-text-secondary-on-light`

## Screenshots

![Screen Shot 2022-09-09 at 9 17 07 AM](https://user-images.githubusercontent.com/55998746/189395507-665c4fe0-9887-4b46-b4e2-c43e22a3271b.png)

![Screen Shot 2022-09-09 at 9 16 05 AM](https://user-images.githubusercontent.com/55998746/189395377-c3271bb6-559f-40c5-80f4-bee7aaf70fd0.png)

**Comment by blackfalcon** [comment]
Why is this marked as `blocked`? What is the issue to be resolved?

**Comment by jdeeezzy** [comment]
@blackfalcon @braven112 Brandon and I started working on this, but came to a decision to run it by June first before making any changes just confirm.

**Comment by leeejune** [comment]
@jdeeezzy and I met to consult the problem and Justin will be unblocking the problem.
