### ISSUE TITLE
popperjs support bib floating outside of container

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-dropdown#171]
## Is your feature request related to a problem? Please describe.

When using the dropdown inside of an element like auro-dialog the dropdown is cutoff if any part of it would naturally be below the dialog.

## Describe the solution you'd like

We want the bib to always show even if it needs to be visible outside the dialog.  When comparing this to how the native `<select>` element works we found that at least on windows the select `<options>` are visible outside of the dialog.

## Describe alternatives you've considered

We could try to calculate how much available space is below the dropdown and place it above but if there isn't enough space above we would also run into this issue.

## Additional context

If popperjs can't handle this natively then pause the work and let's talk about it as a team

You can see an example of the bug here.

https://www.alaskaair.com/search/results?A=1&O=sea&D=las&OD=2023-08-25&OT=Anytime&DD=2023-08-25&DT=Anytime&UPG=none

Scroll down to the bottom of the page and click on the currency converter in the fine print.

- The dropdown initially loads below then once the user scrolls slightly it shifts above.

**Comment by jordanjones243** [comment]
After further investigation, there is currently no quick solution to fix this issue. The nested select element cannot have it's dropdown menu overflow without either changing the overflow behavior of it's parent element or removing it from the DOM and doing absolute positioning of the element (essentially the work that popperJS does for us).

Look at these two PRs to find a workaround solution that can be used to fix the example of this issue:

1. Use `auro-dialog`'s CSS parts to manipulate it's shadow DOM elements
 - https://github.com/AlaskaAirlines/auro-interruption/pull/97
2. An example created in `auro-select` extremely similar to the example of this issue
-  https://github.com/AlaskaAirlines/auro-select/pull/135
