### ISSUE TITLE
Clicking on the x to clear dropdown shows undefined

### ISSUE THREAD

**Issue by vhdinh** [AlaskaAirlines/auro-dropdown#173]
## To Reproduce

1. Go to https://www.alaskaair.com/search
1. Hover over the From destination input box
1. Click on the X
1. See undefined

## Expected behavior
Clicking the X should not show the text undefined

## Screenshots

https://user-images.githubusercontent.com/13775747/200061864-d1607774-038b-4495-bab2-408b020e1400.mov

## Desktop (please complete the following information):

 - OS: OS
 - Browser Chrome, Firefox
 - Version: Chrome[106.0.5249.119], Firefox[106.0.3]

**Comment by blackfalcon** [comment]
@vhdinh are you able to repro this issue on the auro docsite? https://auro.alaskaair.com/components/auro/combobox

**Comment by blackfalcon** [comment]
I have marked this issue as abandoned due to the lack of the author's response. We are currently unable to repro this issue and requested additional support from the author. 

This issue will be closed upon the next review unless we receive a response from the author.
