### ISSUE TITLE
Ascom cannot import bundled assets on legacy circumstances

### ISSUE THREAD

**Issue by anikris1** [AlaskaAirlines/auro-dropdown#199]
### Please verify the version of auro-dropdown you have installed

v2.9.9

### Please describe the bug
We're looking to import the auro-datepicker, auro-combobox &  auro-dropdown into the homelet on the Ascom homepage. 

script tag doesn't seem to import assets after page load event as this is invoked as a Ajax request. so     
we're packaging these assets in CH, but running into issue where auro-dropdown isn't mounted as shown :

 
![image](https://github.com/AlaskaAirlines/auro-dropdown/assets/128737524/b652184c-b1a5-4b73-8af2-13416922c997)

![image](https://github.com/AlaskaAirlines/auro-dropdown/assets/128737524/e84b28cc-e5e9-4b09-b1f6-e17ea38b0362)

![image](https://github.com/AlaskaAirlines/auro-dropdown/assets/128737524/a5f1e277-28f3-47d4-8aaa-702356662eb1)

### Reproducing the error

None

### Expected behavior

auro-dropdown should get imported and rendered. 

### What browsers are you seeing the problem on?

Chrome

**Comment by rdasan-alaska** [comment]
This is in continuation from https://github.com/AlaskaAirlines/auro-datepicker/issues/129

**Comment by blackfalcon** [comment]
@anikris1  and @rdasan-alaska, please add more context regarding how you install these dependencies and your expectations. Running a local test using the CDN installing method, I can not repro an issue with the auro-dropdown element. 

<img width="1586" alt="Screen Shot 2023-06-16 at 12 42 06 PM" src="https://github.com/AlaskaAirlines/auro-dropdown/assets/181089/d98d284a-8492-4a09-8d36-ebe272dbd458">

**Comment by anikris1** [comment]
@blackfalcon we did it in ComponentLibrary  

> npm i

> npm run build

**Comment by gusnaughton** [comment]
@anikris1, when we last discussed, we agreed that using the component hangar to import auro into the modern environment is an antipattern. Is there a reason why we chose to move forward with that strategy I'm not aware of?

**Comment by anikris1** [comment]
@gusnaughton as mentioned script tag doesn't seem to import assets after page load event as this is invoked as a Ajax request. cc: @rdasan-alaska

**Comment by Izook** [comment]
Is there a page or AScom branch where we can see this issue + help investigate?

**Comment by Patrick-Daly-AA** [comment]
@anikris1 , we have recently changed how we are bundling our dependencies on the beta branches of these components.  Are you still encountering this issue?  And if so, could you please try with the Beta versions of Dropdown, Datepicker, and combobox?

**Comment by Patrick-Daly-AA** [comment]
This issue will be solved by the rebuild of the homepage.  If there are any other instances of this happening in the monolith, please create new issues.
