### ISSUE TITLE
The Popup becomes untethered from Dropdown after initial interaction

### ISSUE THREAD

**Issue by dkt2** [AlaskaAirlines/auro-dropdown#212]
### Please verify the version of auro-dropdown you have installed

2.9.11

### Please describe the bug

1. Import Auro Dropdown into React component
2. Load page
3. Click Dropdown
4. Resize browser window
5. Click Dropdown

https://github.com/AlaskaAirlines/auro-dropdown/assets/16234891/ed9b4127-270c-459c-9817-a259a5fbab85

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

The popup sticks to dropdown regardless of browser window size interactions.

### What browsers are you seeing the problem on?

Chrome

**Comment by dkt2** [comment]
@blackfalcon / @Patrick-Daly-AA : are there any pointers for this issues?

**Comment by Patrick-Daly-AA** [comment]
This should be resolved when AlaskaAirlines/auro-form#31 is implemented.  Will keep this open while we complete that work.

**Comment by fajar-apri-alaska** [comment]
Ticket should be closed since this [one](https://github.com/AlaskaAirlines/auro-select/issues/187) is already resolved.

**Comment by blackfalcon** [comment]
> Ticket should be closed since this [one](https://github.com/AlaskaAirlines/auro-select/issues/187) is already resolved.

Closing
