### ISSUE TITLE
Removed linting bypass is causing releases to fail

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-dropdown#222]
### Please verify the version of auro-dropdown you have installed

@latest

### Please describe the bug

Please see this commit https://github.com/AlaskaAirlines/auro-dropdown/commit/d1db5bca8559065dce1f90c7197b40341ef7ec13#diff-ab7bd51ef198950a30a14340022076364f8c8c4701983f13e6a0ed1f0d507691

This update is causing this build error https://github.com/AlaskaAirlines/auro-dropdown/actions/runs/8161376207

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

This update should be reverted to bypass this linting issue.

Releases are to be built without error. 

### Exit criteria

This issue can be closed once the lining bypass has been reverted and the release pipeline will succeed. 

A reason why the linting error is being bypassed versus correct MUST accompany this update. 

Further Discussion is needed for a long term solution across all repositories: https://github.com/AlaskaAirlines/WC-Generator/discussions/523

**Comment by Patrick-Daly-AA** [comment]
NOTE: @blackfalcon create a follow-up issue to fix the underlying problem.  solution for this issue should be to put the ignore back in place.
