### ISSUE TITLE
Name of file is causing issues with SSR support

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-dropdown#230]
### Please verify the version of auro-dropdown you have installed

2.10.6

### Please describe the bug

1. Install dropdown in a SSR project
2. See error

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

Dropdown is successfully installed in SSR projects

### Additional context

<img width="2777" alt="Screenshot 2024-04-24 at 10 22 55 AM" src="https://github.com/AlaskaAirlines/auro-dropdown/assets/55807669/add802f6-e1ad-449c-a017-fe467a6781ac">

**Comment by blackfalcon** [comment]
Please also see this issue for related problems. https://github.com/AlaskaAirlines/auro-select/issues/196

**Comment by jason-capsule42** [comment]
Already fixed as part of another release
