### ISSUE TITLE
a11y role on slot element is causing linting errors

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-dropdown#232]
### Please verify the version of auro-dropdown you have installed

2.10.6

### Please describe the bug

1. Open `auro-dropdown` locally
2. Run command in terminal `npm run linters`
3. See two linting errors that come up

Line of code causing error:
`<slot role="tooltip"></slot>` - Line 445 in `auro-dropdown.js`

Error that appears in terminal:
<img width="667" alt="Screen Shot 2024-06-03 at 11 18 18 AM" src="https://github.com/AlaskaAirlines/auro-dropdown/assets/55807669/6b33350e-1b3a-4baa-bb56-12dfad86af06">

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

All linting tests and build processes complete without errors

**Comment by jason-capsule42** [comment]
This should already be fixed but validate before closing this issue.

**Comment by sun-mota** [comment]
verified this issue is solved with eslint-disable
