### ISSUE TITLE
Make border color of `borderless` version the same color as the background color

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-dropdown#234]
### General Support Request

Currently, the `borderless` version of `auro-dropdown` uses a style rule of `border-color: transparent` to create this effect. If you compare the `bordered` and `borderless` version side by side, the `borderless` version will appear `1px` smaller. We should make it so that these two versions have the exact same dimensions as each other.

### Possible Solution

Create a new token for borders that match the color used for our default white container background (with a value of `#ffffff`) and apply that to the `border-color` of the `borderless` version of dropdown to give it the same dimensional appearance as the `bordered` version.

### Additional context

A new design token needs to be created to achieve this request

**Comment by Patrick-Daly-AA** [comment]
Putting into backlog while we await design input to become available.
