### ISSUE TITLE
auro-dropdown: Full-screen display on mobile devices/breakpoints

### ISSUE THREAD

**Issue by arrenleung** [AlaskaAirlines/auro-dropdown#263]
### Is your feature request related to a problem? Please describe.

When flight search's designers were creating the super menu for filtering results, they originally envisioned a dropdown that would open a full-screen display on mobile devices. Because auro-dropdown did not support this and mobile users were not our priority at the time, we opted to fit everything in the current dropdown popover like so:

![image](https://github.com/user-attachments/assets/2bf6dec1-42db-4d0e-8be5-a7234e5e705e)

Because of E-Commerce's new initiative to be a mobile-first organization, being able to have a full-screen display for auro-dropdown would greatly improve the mobile user experience. Flight search is also looking to revamp the passenger selection dropdown for the mobile experience, as well, which calls for a full-screen dropdown on mobile devices:

![image](https://github.com/user-attachments/assets/5fde1c5f-7b4a-42fe-af57-52bb2640a28d)

### Describe the solution you'd like

- Dropdown content on mobile breakpoints (screen widths of 575px and below) would cover the entire screen
- A close button is added to the dropdown container to allow users to close the dropdown when full-screen

### Describe alternatives you've considered

- Creating an in-house full-screen modal
  - Easy to create a full-screen modal component, but very ugly when trying to integrate it with auro-dropdown

**Comment by Patrick-Daly-AA** [comment]
Closing as a duplicate.  This will be addressed by the work in https://github.com/AlaskaAirlines/auro-form/issues/55
