### ISSUE TITLE
auro-dropdown: onDark styles don't pass to chevron

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-dropdown#33]
## Describe the bug

applying `onDark` to `auro-dropdown` does not apply 'onDark` to the `auro-icon` used for the `chevron` attribute.

## To Reproduce

1. Run the demo
1. Scroll down to the chevron examples
1. Examine the color of the chevron icon

## Expected behavior

Icon should also have `onDark` applied

## Possible solution

Check for both `chevron` and `onDark` attributes on the host element and then dynamically add `onDark`attribute to the chevron 
`auro-icon`.

**Comment by blackfalcon** [comment]
The `chevron` is coming from `auro-input` if I am correct. The `auro-icon` element has a primary color class applied to the icon as a default. To counter this, the `customColor` attribute was created, that when used no other color is applied by default allowing the default fill setting of `currentColor` to be true. 

So by setting the parent color, this should pierce the shadow DOM and paint that element the color intended. 

This is how the calendar icon works with https://input-dateformat-issue72.surge.sh/, inspect on the disabled demo and see that that the disabled color is set at the :host level and is then applied to the icon.
