### ISSUE TITLE
Additional style should not be needed

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-dropdown#39]
https://github.com/AlaskaAirlines/auro-dropdown/blob/5a872847403854bdd065a3f3d224957fad47b1ca/src/auro-dropdown.js#L229

```
style="color: inherit;"
```

This is not needed with the `customColor` attribute. Adding the attribute enables the auro-icon element to pass through the current color.

**Comment by jason-capsule42** [comment]
This is done exactly per the `auro-icon` demo page example code:

https://auro.alaskaair.com/components/auro/icon
<img width="835" alt="Screen Shot 2021-12-02 at 5 40 25 PM" src="https://user-images.githubusercontent.com/23223137/144530181-998f047c-3260-469a-af37-2fd44a4bfe83.png">

**Comment by blackfalcon** [comment]
You have `style="color: inherit;"`. What I am saying is that this is already part of the element's CSS. 

```scss
:host {
  color: currentColor;
  vertical-align: middle;
  line-height: 1;
}
```

The code you are pointing to repaints the icon to be `orange`. I am saying by default the host element will use `customColor` so there is no reason to redefine that.
