### ISSUE TITLE
auro-dropdown: mobile design

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-dropdown#49]
Add to existing Figma blueprint of auro-dropdown to communicate what dropdown looks like on mobile.

**Comment by leeejune** [comment]
Talked to UI designers about this. It would be interesting to have a special mobile interaction for dropdown (using Github as an example).

@braven112 Is this a high priority? Can we can it to a backlog?

**Comment by Patrick-Daly-AA** [comment]
closing.  Work has been tracked under Auro-Select.
