### ISSUE TITLE
Remove halo effect / Support no styled version

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-dropdown#66]
## Describe the bug

In some examples of different triggers, there is a halo effect when clicking on the trigger. Can we remove that? 

## To Reproduce

1. Go to API demo page
1. Click on example with button as trigger
1. See halo

## Expected behavior

No halo

## Screenshots

![Screen Shot 2022-01-11 at 4 24 56 PM](https://user-images.githubusercontent.com/181089/149042258-023e2ccc-1a0d-4b0d-82b4-58ec2aecd219.png)

**Comment by jason-capsule42** [comment]
We had discussed the idea of supporting an attribute that would remove all of our styles like this. I propose look at doing that work instead.

I don't think we should get in the business of trying to smartly control if the focus/active style states.
