### ISSUE TITLE
disabled state

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-dropdown#7]
## Describe the bug

`disabled` needs to be added to the API. This should be able to be passed to slot content for styling purposes and should prevent toggling visibility of the dropdown.

**Comment by steve-nickerson** [comment]
upvote from FlightChange also on this. We need to show Saver Fares in the dropdown disabled for reissue searching if they are saver since that is not allowed and the UI dictates that we show the option so as not to confuse the user.
