### ISSUE TITLE
a11y: dropdown is not after the trigger in the tab order

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-dropdown#73]
## Describe the bug

When I navigate with the keyboard and open the dropdown, I need to tab backwards (Shift + Tab) to get inside the dropdown.

## To Reproduce

1. Go to the [dropdown demo](https://auro.alaskaair.com/components/auro/dropdown)
1. Tab to the dropdown trigger
1. Open the dropdown and press Tab. You are not inside the dropdown and the "see code" accordion is focused instead

## Expected behavior

The dropdown appears after the trigger in the tab order. For the demo page, when I hit Tab after opening the dropdown, the "Dismiss dropdown" inside the dropdown is focused.

**Comment by jason-capsule42** [comment]
Since we are going to be moving to the aria rules implementation of keyboard navigation this will no longer be required.

**Comment by geoffrich** [comment]
@jason-capsule42 can you elaborate on this? Is there an issue open to track this work?

**Comment by blackfalcon** [comment]
@geoffrich there is another track of work related to refactoring the a11y interface of the component where this will be addressed.
