### ISSUE TITLE
Bib specs and design

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-dropdown#79]
## Is your feature request related to a problem? Please describe.

The current dropdown bib and other dropdown bibs have inconsistencies.

## Describe the solution you'd like

Define the design through a blueprint to bring all of the designs together.

**Comment by leeejune** [comment]
https://www.figma.com/file/3TQhiKjQqQOKYqaqcO1zj2/Dropdown?node-id=906%3A753

Added bib specs to "Layout", "Color & Typography", and "Anatomy" sections.

Please review @blackfalcon

**Comment by blackfalcon** [comment]
@leeejune when is a shadow applied to the trigger? What is that use case? 

Also the hex values you have in the design, is there a suggestion to add to the design tokens? Is this update dependent on the work related to defining a shadow standard? 
<img width="1484" alt="Screen Shot 2022-03-04 at 11 37 25 AM" src="https://user-images.githubusercontent.com/181089/156830435-eaad96b2-3f4a-4812-9f2a-c75fc99cc96c.png">

**Comment by leeejune** [comment]
> when is a shadow applied to the trigger? What is that use case?

@blackfalcon The shadow is not applied to the trigger; it was left there as part of the previous concept. I was a bit confused on how we changed the concept from having the trigger carry the shadow for whatever is put as the bib.

If it no longer makes sense, I will remove it.

> Also the hex values you have in the design, is there a suggestion to add to the design tokens? Is this update dependent on the work related to defining a shadow standard?

This update is dependent on the work related to the shadow tokens.

**Comment by blackfalcon** [comment]
> If it no longer makes sense, I will remove it.

Please remove

> This update is dependent on the work related to the shadow tokens.

Please note that this is dependent on other work and link the issue for that work.

**Comment by blackfalcon** [comment]
I marked this issue as BLOCKED per dependency.

**Comment by leeejune** [comment]
Shadow on trigger removed.

**Comment by blackfalcon** [comment]
@leeejune 

1. The shadow definition, is this fraction of a pixel really necessary? 
2. Just making sure, there is no inset padding inside the bib, right?  

<img width="836" alt="Screen Shot 2022-03-10 at 10 54 58 AM" src="https://user-images.githubusercontent.com/181089/157734935-b46910db-49fc-4d70-8abc-1b96696d4f85.png">

**Comment by leeejune** [comment]
@blackfalcon 
1. The fraction is not necessary; it's been overlooked. I will edit that to be 0.1px.
2. I thought for most parts the content will have its own padding for the bib. Would this not be the case?

**Comment by blackfalcon** [comment]
Moving this to IN PROGRESS to do a UI review of the spec and the current version of the dropdown bib.

**Comment by braven112** [comment]
Work left to do:  Update Figma component to use design token and update web component to use the new shadow design token.

**Comment by leeejune** [comment]
Updated shadow token in Figma.

**Comment by blackfalcon** [comment]
I updated the state of this issue. If I understand this correctly, the work to be done is to address the incorrect representation of the design in the component? So, fix a `bug`?

**Comment by Patrick-Daly-AA** [comment]
To the best of our knowledge, all inconsistencies have been addressed.  Closing
