### ISSUE TITLE
Chevron animation on click

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-dropdown#80]
## Is your feature request related to a problem? Please describe.

There is lack of consistency between chevron animations in Auro components.

## Describe the solution you'd like

Come up with a new animation spec (research will be done by Nick King.

## Describe alternatives you've considered

Remove chevron animations in components that use animation.

**Comment by blackfalcon** [comment]
Add me back when a review is needed.

**Comment by Patrick-Daly-AA** [comment]
Closing.  animations for Dropdown are no longer a current part of the spec.
