### ISSUE TITLE
Test custom events 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-dropdown#88]
# General Support Request

While we are meeting our minimum test coverage, essential custom events are not being tested and these are critical parts of the API. 

<img width="689" alt="Screen Shot 2022-03-04 at 3 33 18 PM" src="https://user-images.githubusercontent.com/181089/156855989-71faac61-47bb-48ec-b06e-4ef114ce78c1.png">

## Support request

Write tests that cover the custom events.

**Comment by jason-capsule42** [comment]
Also 

  ```
offClick(event) {
    // Hide the dropdown content if we clicked anywhere outside auro-dropdown
    const expectedIndex = -1;

    if (event.composedPath().indexOf(document.expandedAuroDropdown) === expectedIndex) {
      document.expandedAuroDropdown.hide();
    }
  }
```

**Comment by jordanjones243** [comment]
Fixed during earlier release.
