### ISSUE TITLE
When the dropdown is open via keyboard, content is not accessible 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-dropdown#89]
## Describe the bug

Currently, if a user is only using the dropdown to expose general content that may contain an action, a user cannot access this action via the keyboard. 

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/dropdown
1. Use the keyboard to open a dropdown example
1. Try to access the button within the bib via the keyboard 
1. See error

## Expected behavior

A user should be able to access the content of the bib and apply an action via the keyboard if required.

**Comment by jason-capsule42** [comment]
The content is actually accessible - problem is that the bib content is *before* the dropdown trigger in the DOM. This means  after opening the bib you must shift+tab to get to the bib content.

**Comment by jason-capsule42** [comment]
Similar issue that should be handled is that once the dropdown is open and focus is on content in the bib the `esc` key no longer dismisses the dropdown.
